name: Build Firmware

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git submodules
      run: git submodule update --init --recursive

    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake

    - name: Prepare build script
      run: chmod +x Firmware/src/build.sh

    - name: Clone Pico SDK
      run: git clone https://github.com/raspberrypi/pico-sdk.git Firmware/src/pico-sdk

    - name: Set Pico SDK path
      run: echo "export PICO_SDK_PATH=$PWD/Firmware/src/pico-sdk" >> $GITHUB_ENV

    - name: Run build script
      run: cd ./Firmware/src && ./build.sh
      shell: bash